name: Python Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run mypy
        run: uv run mypy

      - name: Run ruff formatter
        run: uv run ruff format

      - name: Run ruff linter
        run: uv run ruff check

      - name: Debug event name
        run: echo 'Event name -> ${{ github.event_name }}'

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run tests
        run: uv run pytest --oracles skip -n auto
