name: Python Tests with Modal

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]  # Runs on merge to main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Authenticate Modal
        shell: bash -l {0}
        run: uv run modal token set --token-id ${{ secrets.MODAL_API_TOKEN_ID }} --token-secret ${{ secrets.MODAL_API_TOKEN_SECRET }}

      - name: Run tests
        run: uv run pytest --oracles modal -n auto
